core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quiz.urls")),
]

quiz/urls.py
from django.urls import path
from .views import (
    HomeView,
    CreateQuizView,
    QuizDetailView,
    QuizDeleteView,
    AddQuestionView,
    EditQuizView,
    QuizResultsView,
    take_quiz,
    get_question,
    submit_answer,
)


app_name = "quiz"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("create-quiz/", CreateQuizView.as_view(), name="create-quiz"),
    path("quiz/<str:slug>/", QuizDetailView.as_view(), name="quiz-detail"),
    path("quiz/<str:slug>/delete/", QuizDeleteView.as_view(), name="quiz-delete"),
    path("quiz/<str:slug>/edit/", EditQuizView.as_view(), name="edit-quiz"),
    path(
        "quiz/<str:slug>/add-question/", AddQuestionView.as_view(), name="add-question"
    ),
    path("quiz/<str:slug>/take-quiz/", take_quiz, name="take-quiz"),
    path("quiz/<str:slug>/question/", get_question, name="get-question"),
    path(
        "quiz/<str:slug>/submit-answer/<int:question_id>/",
        submit_answer,
        name="submit-answer",
    ),
    path("quiz/<str:slug>/results/", QuizResultsView.as_view(), name="quiz-results"),
]

quiz/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
import string
from django.utils.crypto import get_random_string


def unique_slugify(instance, slug):
    model = instance.__class__
    unique_slug = slug
    while model.objects.filter(slug=unique_slug).exists() or unique_slug == "":
        allowed_chars = string.ascii_letters + string.digits + "_-"
        unique_slug = slug + get_random_string(length=6, allowed_chars=allowed_chars)

    return unique_slug


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Quiz(BaseModel):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=255)
    description = models.TextField(null=True, blank=True)
    is_published = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    is_timed = models.BooleanField(default=True)
    time_limit = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = "Quizzes"

    def __str__(self) -> str:
        return self.title

    # get quiz participants
    def get_participants(self):
        return self.results.all().values_list("user", flat=True)

    def save(self, *args, **kwargs) -> None:
        if self.pk is None:
            # set slug when first creating a quiz object
            slug = slugify(self.title, allow_unicode=True)
            self.slug = unique_slugify(self, slug)
        super(Quiz, self).save(*args, **kwargs)


class QuizResult(BaseModel):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="results")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    answers = models.ManyToManyField("QuestionAnswer")

    def __str__(self) -> str:
        return f"{self.user.username} - {self.quiz}"


class Question(models.Model):
    text = models.TextField()
    duration = models.PositiveIntegerField(default=60)
    correct_short_answer = models.CharField(max_length=50, blank=True, null=True)
    explanation = models.TextField(blank=True, null=True)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="questions")
    QuestionType = models.TextChoices("QuestionType", "MULTIPLE_CHOICE SHORT_ANSWER")
    question_type = models.CharField(
        max_length=15,
        choices=QuestionType.choices,
        default=QuestionType.MULTIPLE_CHOICE,
    )

    def get_question_number(self):
        return list(self.quiz.questions.order_by("id")).index(self) + 1

    def __str__(self) -> str:
        return self.text


class MultipleChoice(models.Model):
    text = models.CharField(max_length=100)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="choices"
    )
    CORRECT_INCORRECT_CHOICES = ((True, "Correct"), (False, "Incorrect"))
    is_correct = models.BooleanField(choices=CORRECT_INCORRECT_CHOICES, default=False)

    def __str__(self) -> str:
        return self.text


class QuestionAnswer(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers"
    )
    multiple_choice = models.ManyToManyField(MultipleChoice)
    short_answer = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.user.username} - {self.question}"

quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.core.cache import cache
from .models import Quiz, QuizResult
from .forms import QuizForm, AddQuestionForm, MultipleChoiceFormSet, QuestionAnswerForm


class HomeView(generic.TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["quizzes"] = Quiz.objects.filter(is_published=True).order_by(
            "-created_at"
        )
        return context


class CreateQuizView(LoginRequiredMixin, generic.CreateView):
    model = Quiz
    form_class = QuizForm
    template_name = "quiz/create_quiz.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.save()
        messages.success(self.request, "Quiz created successfully")
        return redirect(
            reverse("quiz:quiz-detail", kwargs={"slug": form.instance.slug})
        )


class QuizDetailView(LoginRequiredMixin, generic.DetailView):
    model = Quiz
    template_name = "quiz/quiz_detail.html"


class QuizDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Quiz
    success_url = reverse_lazy("quiz:home")
    success_message = "Quiz was Deleted successfully"

    def test_func(self):
        return self.get_object().created_by == self.request.user


class AddQuestionView(generic.View):
    def render_form_page_response(self, request, quiz, question_form, choice_formset):
        # render the form page with given context
        return render(
            request,
            template_name="quiz/add_question.html",
            context={
                "quiz": quiz,
                "question_form": question_form,
                "choice_formset": choice_formset,
            },
        )

    def get(self, request, slug):
        quiz = get_object_or_404(Quiz, slug=slug)
        question_form = AddQuestionForm()
        choice_formset = MultipleChoiceFormSet(prefix="choice")

        return self.render_form_page_response(
            request, quiz, question_form, choice_formset
        )

    def post(self, request, slug):
        quiz = get_object_or_404(Quiz, slug=slug)
        question_form = AddQuestionForm(request.POST)
        choice_formset = MultipleChoiceFormSet(prefix="choice")

        if question_form.is_valid():
            question = question_form.save(commit=False)
            question.quiz = quiz
            choice_formset = MultipleChoiceFormSet(request.POST, prefix="choice")

            if (
                question.question_type == "MULTIPLE_CHOICE"
                and choice_formset.is_valid()
            ):
                # save question with associated choices
                question.save()
                choices = choice_formset.save(commit=False)

                for choice in choices:
                    choice.question = question
                    choice.save()

                messages.success(request, "Question created successfully")
                return redirect(reverse("quiz:quiz-detail", kwargs={"slug": quiz.slug}))

            elif question.question_type == "SHORT_ANSWER":
                question.save()

                messages.success(request, "Question created successfully")
                return redirect(reverse("quiz:quiz-detail", kwargs={"slug": quiz.slug}))

        return self.render_form_page_response(
            request, quiz, question_form, choice_formset
        )


class EditQuizView(generic.UpdateView):
    model = Quiz
    form_class = QuizForm
    template_name = "quiz/edit_quiz.html"
    # success_url = reverse("my-quiz")

    def get_success_url(self) -> str:
        slug = self.kwargs.get("slug")
        return reverse("quiz:quiz-detail", kwargs={"slug": slug})


def get_question_form(question, user, post_data=None):
    instance = None
    try:
        instance = question.answers.get(user=user)
    except:
        pass

    return QuestionAnswerForm(question, post_data)


def take_quiz(request, slug):
    quiz = get_object_or_404(Quiz, slug=slug)
    QuizResult.objects.get_or_create(quiz=quiz, user=request.user)

    return render(request, "quiz/partials/take_quiz_content.html", {"quiz": quiz})


def get_question(request, slug):
    quiz = get_object_or_404(Quiz, slug=slug)
    questions = quiz.questions.all()
    question = questions.first()

    form = QuestionAnswerForm(question, session=request.session)
    question_number = list(questions).index(question) + 1

    return render(
        request,
        "quiz/partials/question.html",
        {"question": question, "form": form, "question_number": question_number},
    )


def submit_answer(request, slug, question_id):
    quiz = get_object_or_404(Quiz, slug=slug)
    question = get_object_or_404(quiz.questions, id=question_id)

    if request.method == "POST":
        form_action = request.POST.get("form_action", "").lower()

        if "back" in form_action:
            question = quiz.questions.filter(id__lt=question_id).last()
            form = QuestionAnswerForm(question, session=request.session)
        elif "skip" in form_action:
            question = quiz.questions.filter(id__gt=question_id).first()
            form = QuestionAnswerForm(question, session=request.session)
        elif "continue" in form_action:
            form = QuestionAnswerForm(
                question, session=request.session, data=request.POST
            )
            if form.is_valid():
                form.cache_answer(request.session)
                question = quiz.questions.filter(id__gt=question_id).first()
        elif "finish" in form_action:
            form = QuestionAnswerForm(
                question, session=request.session, data=request.POST
            )
            form.save_answer(request.user)
            for key in cache._cache.keys():
                if request.session.session_key in key:
                    cache.delete(key)

            response = HttpResponse()
            response["HX-Redirect"] = reverse(
                "quiz:quiz-results", kwargs={"slug": slug}
            )
            return response

    error = None
    if form.errors:
        error = form.non_field_errors()

    form = QuestionAnswerForm(question, session=request.session)
    return render(
        request,
        "quiz/partials/question.html",
        {"question": question, "form": form, "error": error},
    )


class QuizResultsView(generic.TemplateView):
    template_name = "quiz/quiz_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["quiz"] = Quiz.objects.get(slug=self.kwargs["slug"])
        return context

templates/quiz/partials/question.html
<section id="question" class="w-3/4 flex flex-col border p-8 rounded">
    <div id="timeout-overlay"
         class="bg-gray-800 text-gray-100 absolute w-screen h-screen top-0 left-0 bg-opacity-90 hidden">
        <div class="flex flex-col mt-28">
            <p class="mx-auto mb-5 text-6xl font-bold">Time out</p>
            <p class="mx-auto mb-5 text-lg">You have run out of time given to take "{{ question.quiz.title }}" Quiz!</p>
            <div class="flex justify-center gap-5 items-center">
                <a href="{% url "quiz:quiz-detail" slug=question.quiz.slug %}"
                   class="bg-blue-500 hover:ring-2 focus:ring-2 rounded p-2">Retake Quiz</a>
                <a href="{% url "quiz:home" %}" class="underline text-blue-400">Go Home</a>
            </div>
        </div>
    </div>
    <div class="question-text">
        <p class="text-xl font-bold underline uppercase">
            Question {{ question.get_question_number }}/{{ question.quiz.questions.count }}
        </p>
        <p class="text-3xl font-bold">{{ question.text }}</p>
        <p class="text-xs uppercase font-bold text-gray-400">{{ question.get_question_type_display }}</p>
    </div>
    <hr class="my-3">
    <form hx-post="{% url 'quiz:submit-answer' slug=question.quiz.slug question_id=question.id %}"
          hx-target="#question"
          hx-swap="outerHTML">
        {% csrf_token %}
        {% if question.question_type == 'MULTIPLE_CHOICE' %}
            <div class="flex flex-col mt-3">
                {% for choices in form %}
                    {% for choice in choices %}
                        <div class="bg-gray-500/30 hover:bg-gray-500/20 transition-all mb-3 rounded-lg p-2 flex items-center gap-4 cursor-pointer select-none font-semibold text-lg"
                             onclick="toggleCheckbox(this)">{{ choice }}</div>
                    {% endfor %}
                {% endfor %}
            </div>
        {% elif question.question_type == 'SHORT_ANSWER' %}
            {{ form.short_answer }}
        {% endif %}
        {% if error %}<div class="error text-red-400">{{ error }}</div>{% endif %}
        <hr class="my-3">
        <div class="flex">
            <input type="submit"
                   name="form_action"
                   value="<- Back"
                   class="my-2 rounded-lg border-2 border-gray-600 p-2 text-lg text-gray-600 hover:text-sky-200 hover:bg-sky-700 transition-colors focus:outline-double focus:ring focus:ring-3 font-semibold cursor-pointer {% if question.get_question_number == 1 %}hidden{% endif %} ">
            <div class="ms-auto flex gap-3">
                <input type="submit"
                       name="form_action"
                       class="my-2 rounded-lg bg-sky-600 p-2 text-lg text-sky-200 hover:bg-sky-700 transition-colors focus:outline-double focus:ring focus:ring-3 font-semibold cursor-pointer {% if question.get_question_number == question.quiz.questions.count %}hidden{% endif %}"
                       value="-> Continue">
                <input type="submit"
                       class="underline font-thin text-sky-600 underline-offset-4 cursor-pointer {% if question.get_question_number == question.quiz.questions.count %}hidden{% endif %}"
                       name="form_action"
                       value="Skip">
                <input type="submit"
                       name="form_action"
                       class="my-2 rounded-lg bg-sky-600 py-1 px-3 text-lg text-sky-200 hover:bg-sky-700 transition-colors focus:outline-double focus:ring focus:ring-3 font-semibold cursor-pointer {% if question.get_question_number != question.quiz.questions.count %}hidden{% endif %}"
                       value="✓ Finish">
            </div>
        </div>
    </form>
</section>

templates/quiz/partials/quiz_countdown.html
<section class="w-1/4 rounded border p-4" id="quiz-countdown">
    <p id="countdown" class="text-4xl font- flex justify-center my-6 mb-8">{{ quiz.time_limit }}</p>
    <p class="uppercase text-sm font-bold">Question 3/12</p>
    <hr class="mb-2">
    <p class="font-semibold text-lg">{{ quiz.title }}</p>
    <div class="flex">
        <span class="border-gray-200 border"></span>
        <p class="text-sm ms-2">{{ quiz.description }}</p>
    </div>
    {% comment %} create countdown, every 5 seconds call quiz backend to register the countdown to db {% endcomment %}
</section>

templates/quiz/partials/take_quiz_content.html
{% load quiz_tags %}
<div id="quiz-content" class="modal-content p-4 w-full">
    <div class="flex gap-4 my-16 mx-36">
        <section class="w-3/4 flex flex-col border p-8 rounded"
                 id="question"
                 hx-get="{% url 'quiz:get-question' slug=quiz.slug %}"
                 hx-swap="outerHTML"
                 hx-trigger="revealed"
                 _="on htmx:afterRequest startCountdown()">
            {% comment %} question target {% endcomment %}
        </section>
        <section class="w-1/4 rounded border p-4" id="quiz-countdown">
            <input type="hidden" name='countdown' value={{ quiz.time_limit }}>
            <p id="countdown"
               class="text-4xl font-bold text-gray-600 flex justify-center my-6 mb-8">
                {{ quiz.time_limit|format_seconds }}
            </p>
            <hr class="mb-2">
            <p class="font-semibold text-lg">{{ quiz.title }}</p>
            <div class="flex">
                <span class="border-gray-200 border"></span>
                <p class="text-sm ms-2">{{ quiz.description }}</p>
            </div>
        </section>
    </div>
</div>