core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quiz.urls")),
]

quiz/urls.py
from django.urls import path
from .views import (
    HomeView,
    CreateQuizView,
    QuizDetailView,
    QuizDeleteView,
    AddQuestionView,
    EditQuizView,
    QuizResultsView,
    take_quiz,
    get_question,
    submit_answer,
)


app_name = "quiz"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("create-quiz/", CreateQuizView.as_view(), name="create-quiz"),
    path("quiz/<str:slug>/", QuizDetailView.as_view(), name="quiz-detail"),
    path("quiz/<str:slug>/delete/", QuizDeleteView.as_view(), name="quiz-delete"),
    path("quiz/<str:slug>/edit/", EditQuizView.as_view(), name="edit-quiz"),
    path(
        "quiz/<str:slug>/add-question/", AddQuestionView.as_view(), name="add-question"
    ),
    path("quiz/<str:slug>/take-quiz/", take_quiz, name="take-quiz"),
    path("quiz/<str:slug>/question/", get_question, name="get-question"),
    path(
        "quiz/<str:slug>/submit-answer/<int:question_id>/",
        submit_answer,
        name="submit-answer",
    ),
    path("quiz/<str:slug>/results/", QuizResultsView.as_view(), name="quiz-results"),
]

quiz/forms.py
from typing import Any
from django import forms
from django.core.cache import cache
from .models import Quiz, Question, MultipleChoice, QuestionAnswer


class BaseStyledModelForm(forms.ModelForm):
    default_widget_attrs = {
        "class": "border bg-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
    }

    def __init__(self, *args, **kwargs):
        super(BaseStyledModelForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.style_field(field_name)

    def style_field(self, field_name):
        field = self.fields.get(field_name)

        if field:
            field.widget.attrs.update(self.default_widget_attrs)


class QuizForm(BaseStyledModelForm):
    class Meta:
        model = Quiz
        fields = ("title", "description")
        widgets = {
            "title": forms.TextInput(attrs={"placeholder": "Enter Quiz Title"}),
            "description": forms.Textarea(attrs={"placeholder": "Enter description"}),
        }

    def __init__(self, *args, **kwargs) -> None:
        super(QuizForm, self).__init__(*args, **kwargs)
        description_field = self.fields.get("description")
        description_field.widget.attrs["class"] += " h-28"


class MultipleChoiceForm(BaseStyledModelForm):
    class Meta:
        model = MultipleChoice
        fields = ("text", "is_correct")
        widgets = {"text": forms.TextInput(attrs={"placeholder": "Enter choice"})}

    def __init__(self, *args, **kwargs) -> None:
        super(MultipleChoiceForm, self).__init__(*args, **kwargs)
        text_field = self.fields.get("text")
        text_field.widget.attrs["class"] += " w-full"

        correct_field = self.fields.get("is_correct")
        correct_field.widget.attrs["class"] += " flex-1"


class BaseFormSet(forms.BaseInlineFormSet):
    def clean(self):
        non_empty_texts_count = sum(
            1 for form in self.forms if form.cleaned_data.get("text")
        )
        correct_choices_count = sum(
            1 for form in self.forms if form.cleaned_data.get("is_correct")
        )

        if non_empty_texts_count < 2:
            raise forms.ValidationError(
                '"Multiple Choice" type questions must have at least 2 Choices'
            )

        if correct_choices_count < 1:
            raise forms.ValidationError("Question must have atleast one correct choice")


MultipleChoiceFormSet = forms.inlineformset_factory(
    Question,
    MultipleChoice,
    form=MultipleChoiceForm,
    formset=BaseFormSet,
    min_num=2,
    max_num=10,
    extra=1,
)


class AddQuestionForm(BaseStyledModelForm):
    class Meta:
        model = Question
        fields = (
            "question_type",
            "text",
            "duration",
            "correct_short_answer",
            "explanation",
        )
        widgets = {
            "text": forms.Textarea(attrs={"placeholder": "Enter question text"}),
            "correct_short_answer": forms.TextInput(
                attrs={"placeholder": "Enter answer"}
            ),
            "explanation": forms.Textarea(
                attrs={"placeholder": "Enter explanation for your answer"}
            ),
        }

    def __init__(self, *args, **kwargs) -> None:
        super(AddQuestionForm, self).__init__(*args, **kwargs)
        text_field = self.fields.get("text")
        text_field.widget.attrs["class"] += " h-14"

        correct_short_answer_field = self.fields.get("correct_short_answer")
        correct_short_answer_field.widget.attrs["class"] += " w-full"

        expalanation_field = self.fields.get("explanation")
        expalanation_field.widget.attrs["class"] += " h-20"

    def clean(self) -> dict[str, Any]:
        cleaned_data = super().clean()
        correct_short_answer = cleaned_data.get("correct_short_answer")

        if (
            cleaned_data.get("question_type") == "SHORT_ANSWER"
            and not correct_short_answer
        ):
            self.add_error("correct_short_answer", "Answer field cannot be empty")
            self.fields["correct_short_answer"].widget.attrs[
                "class"
            ] += " border-red-600 focus:ring-red-600"

        return cleaned_data


class QuestionAnswerForm(forms.ModelForm):
    def __init__(self, question, session, *args, **kwargs) -> None:
        self.question = question
        super(QuestionAnswerForm, self).__init__(*args, **kwargs)
        if question:
            if question.question_type == "MULTIPLE_CHOICE":
                del self.fields["short_answer"]
                self.fields["multiple_choice"] = forms.ModelMultipleChoiceField(
                    widget=forms.CheckboxSelectMultiple(
                        attrs={
                            "class": "checked:bg-blue-500 checked:border-transparent checked:text-blue-600 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-1 p-2 pointer-events-none me-2"
                        },
                    ),
                    initial=cache.get(
                        f"{session.session_key}_{self.question.id}_answer"
                    ),
                    queryset=MultipleChoice.objects.filter(question=question),
                )
            elif question.question_type == "SHORT_ANSWER":
                self.fields["short_answer"].initial = cache.get(
                    f"{session.session_key}_{self.question.id}_answer"
                )
                del self.fields["multiple_choice"]

    def save_answer(self, user):
        self.instance.user = user
        self.instance.question = self.question
        self.save()

    def cache_answer(self, session):
        question_type = self.question.question_type.lower()
        answer = self.cleaned_data.get(question_type)

        if self.question.question_type == "MULTIPLE_CHOICE":
            answer = [c.id for c in answer]

        cache.set(f"{session.session_key}_{self.question.id}_answer", answer)
        session[f"{self.question.id}_answer"] = answer

    def clean(self) -> dict[str, Any]:
        cleaned_data = super().clean()
        # check if no choice is selected or no short answer is provided
        if self.question.question_type == "MULTIPLE_CHOICE":
            if not cleaned_data.get("multiple_choice"):
                raise forms.ValidationError("Please select a choice")
        elif self.question.question_type == "SHORT_ANSWER":
            if not cleaned_data.get("short_answer"):
                raise forms.ValidationError("Please provide a short answer")

        return cleaned_data

    class Meta:
        model = QuestionAnswer
        fields = ("multiple_choice", "short_answer")
        widgets = {
            "short_answer": forms.TextInput(
                attrs={
                    "placeholder": "Enter answer",
                    "class": "border bg-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent",
                }
            )
        }

quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.core.cache import cache
from .models import Quiz, QuizResult
from .forms import QuizForm, AddQuestionForm, MultipleChoiceFormSet, QuestionAnswerForm


class HomeView(generic.TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["quizzes"] = Quiz.objects.filter(is_published=True).order_by(
            "-created_at"
        )
        return context


class CreateQuizView(LoginRequiredMixin, generic.CreateView):
    model = Quiz
    form_class = QuizForm
    template_name = "quiz/create_quiz.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.save()
        messages.success(self.request, "Quiz created successfully")
        return redirect(
            reverse("quiz:quiz-detail", kwargs={"slug": form.instance.slug})
        )


class QuizDetailView(LoginRequiredMixin, generic.DetailView):
    model = Quiz
    template_name = "quiz/quiz_detail.html"


class QuizDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Quiz
    success_url = reverse_lazy("quiz:home")
    success_message = "Quiz was Deleted successfully"

    def test_func(self):
        return self.get_object().created_by == self.request.user


class AddQuestionView(generic.View):
    def render_form_page_response(self, request, quiz, question_form, choice_formset):
        # render the form page with given context
        return render(
            request,
            template_name="quiz/add_question.html",
            context={
                "quiz": quiz,
                "question_form": question_form,
                "choice_formset": choice_formset,
            },
        )

    def get(self, request, slug):
        quiz = get_object_or_404(Quiz, slug=slug)
        question_form = AddQuestionForm()
        choice_formset = MultipleChoiceFormSet(prefix="choice")

        return self.render_form_page_response(
            request, quiz, question_form, choice_formset
        )

    def post(self, request, slug):
        quiz = get_object_or_404(Quiz, slug=slug)
        question_form = AddQuestionForm(request.POST)
        choice_formset = MultipleChoiceFormSet(prefix="choice")

        if question_form.is_valid():
            question = question_form.save(commit=False)
            question.quiz = quiz
            choice_formset = MultipleChoiceFormSet(request.POST, prefix="choice")

            if (
                question.question_type == "MULTIPLE_CHOICE"
                and choice_formset.is_valid()
            ):
                # save question with associated choices
                question.save()
                choices = choice_formset.save(commit=False)

                for choice in choices:
                    choice.question = question
                    choice.save()

                messages.success(request, "Question created successfully")
                return redirect(reverse("quiz:quiz-detail", kwargs={"slug": quiz.slug}))

            elif question.question_type == "SHORT_ANSWER":
                question.save()

                messages.success(request, "Question created successfully")
                return redirect(reverse("quiz:quiz-detail", kwargs={"slug": quiz.slug}))

        return self.render_form_page_response(
            request, quiz, question_form, choice_formset
        )


class EditQuizView(generic.UpdateView):
    model = Quiz
    form_class = QuizForm
    template_name = "quiz/edit_quiz.html"
    # success_url = reverse("my-quiz")

    def get_success_url(self) -> str:
        slug = self.kwargs.get("slug")
        return reverse("quiz:quiz-detail", kwargs={"slug": slug})


def get_question_form(question, user, post_data=None):
    instance = None
    try:
        instance = question.answers.get(user=user)
    except:
        pass

    return QuestionAnswerForm(question, post_data)


def take_quiz(request, slug):
    quiz = get_object_or_404(Quiz, slug=slug)
    QuizResult.objects.get_or_create(quiz=quiz, user=request.user)

    return render(request, "quiz/partials/take_quiz_content.html", {"quiz": quiz})


def get_question(request, slug):
    quiz = get_object_or_404(Quiz, slug=slug)
    questions = quiz.questions.all()
    question = questions.first()

    form = QuestionAnswerForm(question, session=request.session)
    question_number = list(questions).index(question) + 1

    return render(
        request,
        "quiz/partials/question.html",
        {"question": question, "form": form, "question_number": question_number},
    )


def submit_answer(request, slug, question_id):
    quiz = get_object_or_404(Quiz, slug=slug)
    question = get_object_or_404(quiz.questions, id=question_id)

    if request.method == "POST":
        form_action = request.POST.get("form_action", "").lower()

        if "back" in form_action:
            question = quiz.questions.filter(id__lt=question_id).last()
            form = QuestionAnswerForm(question, session=request.session)
        elif "skip" in form_action:
            question = quiz.questions.filter(id__gt=question_id).first()
            form = QuestionAnswerForm(question, session=request.session)
        elif "continue" in form_action:
            form = QuestionAnswerForm(
                question, session=request.session, data=request.POST
            )
            if form.is_valid():
                form.cache_answer(request.session)
                question = quiz.questions.filter(id__gt=question_id).first()
        elif "finish" in form_action:
            form = QuestionAnswerForm(
                question, session=request.session, data=request.POST
            )
            form.save_answer(request.user)
            for key in cache._cache.keys():
                if request.session.session_key in key:
                    cache.delete(key)

            response = HttpResponse()
            response["HX-Redirect"] = reverse(
                "quiz:quiz-results", kwargs={"slug": slug}
            )
            return response

    error = None
    if form.errors:
        error = form.non_field_errors()

    form = QuestionAnswerForm(question, session=request.session)
    return render(
        request,
        "quiz/partials/question.html",
        {"question": question, "form": form, "error": error},
    )


class QuizResultsView(generic.TemplateView):
    template_name = "quiz/quiz_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["quiz"] = Quiz.objects.get(slug=self.kwargs["slug"])
        return context

templates/quiz/create_quiz.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Create Quiz
{% endblock title %}
{% block content %}
    <div class="mt-16 flex justify-center">
        <div class="rounded-lg p-6 mx-auto border shadow-sm bg-white">
            <p class="form-title text-4xl font-semibold border-b mb-4">Create Quiz</p>
            <form method="post"
                  action="{% url 'quiz:create-quiz' %}"
                  class="flex flex-col">
                {% csrf_token %}
                <div class="flex flex-col space-y-3 mb-3">
                    <div class="flex flex-col">
                        <p class="text-sm font-semibold uppercase">Title</p>
                        {{ form.title }}
                    </div>
                    <div class="flex flex-col">
                        <p class="text-sm font-semibold uppercase">Description</p>
                        {{ form.description }}
                    </div>
                </div>
                <button class="rounded w-fit ms-auto p-2 bg-sky-700 text-white font-semibold hover:bg-sky-800 transition-colors hover:shadow">
                    <span class="flex gap-1">
                        <i class="bi bi-arrow-right"></i>
                        <span>Continue</span>
                    </span>
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/quiz/delete_quiz_modal.html
{% extends "modal_base.html" %}
{% block modal_title %}
    Delete Quiz?
{% endblock modal_title %}
{% block modal_content %}
    Are you sure you want to delete "{{ quiz_title }}"?
{% endblock modal_content %}
{% block modal_footer %}
    <div id="hs-basic-modal"
         class="hs-overlay hidden size-full fixed top-0 start-0 z-[60] overflow-x-hidden overflow-y-auto pointer-events-none">
        <div class="hs-overlay-open:opacity-100 hs-overlay-open:duration-500 opacity-0 transition-all sm:max-w-lg sm:w-full m-3 sm:mx-auto">
            <div class="flex flex-col bg-white border shadow-sm rounded-xl pointer-events-auto dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
                <div class="flex justify-between items-center py-3 px-4 border-b dark:border-gray-700">
                    <h3 class="font-bold text-gray-800 dark:text-white">Modal title</h3>
                    <button type="button"
                            class="flex justify-center items-center size-7 text-sm font-semibold rounded-full border border-transparent text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-white dark:hover:bg-gray-700 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600"
                            data-hs-overlay="#hs-basic-modal">
                        <span class="sr-only">Close</span>
                        <svg class="flex-shrink-0 size-4"
                             xmlns="http://www.w3.org/2000/svg"
                             width="24"
                             height="24"
                             viewBox="0 0 24 24"
                             fill="none"
                             stroke="currentColor"
                             stroke-width="2"
                             stroke-linecap="round"
                             stroke-linejoin="round">
                            <path d="M18 6 6 18" />
                            <path d="m6 6 12 12" />
                        </svg>
                    </button>
                </div>
                <div class="p-4 overflow-y-auto">
                    <p class="mt-1 text-gray-800 dark:text-gray-400">
                        This is a wider card with supporting text below as a natural lead-in to additional content.
                    </p>
                </div>
                <div class="flex justify-end items-center gap-x-2 py-3 px-4 border-t dark:border-gray-700">
                    <button type="button"
                            class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-white dark:hover:bg-gray-800 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600"
                            data-hs-overlay="#hs-basic-modal">Close</button>
                    <a class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600"
                       href="#">Save changes</a>
                </div>
            </div>
        </div>
    </div>
    <div class="flex gap-2">
        <form class="ms-auto"
              method="post"
              action="{% url 'quiz:quiz-delete' slug=quiz.slug %}">
            {% csrf_token %}
            <button class="bg-rose-800 text-rose-200 p-2 font-semibold rounded focus:ring-2 text-sm">
                <i class="bi bi-trash"></i>
                Confirm Delete
            </button>
        </form>
        <button class="bg-gray-600 p-2 font-semibold rounded focus:ring-2 text-white text-sm"
                onclick="closeModal('delete_quiz_modal')">
            <i class="bi bi-x"></i>
            Close
        </button>
    </div>
{% endblock modal_footer %}

templates/quiz/my_quiz.html
{% extends "base.html" %}
{% block title %}
    {{ quiz.title }}
{% endblock title %}
{% block content %}
    <div class="p-8 mt-6 lg:ms-16">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="messages bg-green-900/30 text-green-900 border rounded-lg px-4 py-2 flex gap-3 items-center mb-2">
                        <i class="bi bi-check-circle"></i>
                        <p>{{ message }}</p>
                        <button class="underline ms-auto bi bi-x text-2xl"
                                id="question-form-error-close"></button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <div class="flex items-center">
            <div class="flex flex-col gap-1">
                <p class="font-semibold text-2xl text-sky-950">{{ quiz.title }}</p>
                <p class="text-sm">{{ quiz.description }}</p>
                <div class="flex">
                    <a class="bi bi-pen text-sky-700 text-sm underline"
                       href="{% url 'quiz:edit-quiz' slug=quiz.slug %}">Edit quiz</a>
                    <a class="ms-3 bi bi-trash text-red-700 text-sm underline" href="#">Delete quiz</a>
                </div>
            </div>
            <div class="flex flex-col ms-auto w-fit gap-2">
                <button class="ms-auto text-sm uppercase text-sky-600 underline"
                        title="{% for participant in quiz.participants.all %}{{ participant }},{% endfor %}">
                    {{ quiz.participants.count }} participants
                </button>
            </div>
        </div>
        <hr class="mt-2 mb-3">
        <div class="questions mb-3 grid lg:grid-cols-2 sm:grid-cols-1 gap-4">
            {% if quiz.questions.count %}
                {% for question in quiz.questions.all %}
                    <div class="shadow border rounded-lg p-3 mb-3 h-fit">
                        <div class="flex flex-col">
                            <p class="text-xl">{{ question }}</p>
                            {% if question.question_type == 'MULTIPLE_CHOICE' %}
                                <p class="text-xs uppercase font-semibold opacity-40">Multiple Choice</p>
                                <hr class="mb-3">
                                <div class="choice-row text-sm flex  flex-col gap-1">
                                    {% for choice in question.choices.all %}
                                        {% if choice.is_correct %}
                                            <div class="bg-green-400/60 rounded p-1 ps-2 text-green-900 flex gap-2 font-semibold">
                                                <p>{{ choice.text }}</p>
                                                <p>(Correct)</p>
                                            </div>
                                        {% else %}
                                            <div class="bg-gray-400/60 rounded p-1 ps-2 text-gray-900 flex gap-2 font-semibold">
                                                <p>{{ choice.text }}</p>
                                                <p>(Incorrect)</p>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            {% endif %}
                            {% if question.question_type == 'SHORT_ANSWER' %}
                                <p class="text-xs uppercase font-semibold opacity-40">Short Answer</p>
                                <hr class="my-2">
                                <div class="flex gap-2 items-center">
                                    <p class="font-semibold uppercase text-sm">Correct answer:</p>
                                    <p>{{ question.correct_short_answer }}</p>
                                </div>
                            {% endif %}
                            <hr class="my-2">
                            <div class="flex gap-2">
                                <button class="text-xs ms-auto bg-red-700 hover:bg-red-800 rounded w-fit p-1 text-white focus:ring-2 focus:ring-red-700/30">
                                    <i class="bi bi-x"></i>
                                    Delete
                                </button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="no-questions flex text-lg mt-6 mb-4">Quiz have no questions</div>
            {% endif %}
        </div>
        <a type="button"
           class="my-2 rounded-full bg-sky-600 py-2 px-4 text-sky-200 hover:bg-sky-700 transition-colors focus:outline-double focus:ring focus:ring-3 font-semibold"
           id="add-question-btn"
           href="{% url 'quiz:add-question' slug=quiz.slug %}">
            <i class="bi bi-plus-circle"></i>
            Add Question
        </a>
    </div>
{% endblock content %}

templates/quiz/quiz_detail.html
{% extends "base.html" %}
{% load quiz_tags %}
{% block title %}
    {{ quiz.title }}
{% endblock title %}
{% block content %}
    <div class="p-8 mt-6 lg:ms-16">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="messages bg-green-900/30 text-green-900 border border-green-700 rounded-lg px-4 py-2 flex gap-3 items-center mb-2">
                        <i class="bi bi-check-circle"></i>
                        <p>{{ message }}</p>
                        <button class="underline ms-auto bi bi-x text-2xl"
                                id="question-form-error-close"></button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <div class="bg-gray-100 rounded-lg p-3 border shadow">
            <div class="flex flex-col gap-1">
                <p class="text-3xl font-semibold">{{ quiz.title }}</p>
                <p>{{ quiz.description }}</p>
                {% if quiz.created_by == request.user %}
                    <div class="flex gap-3">
                        <a href="{% url 'quiz:edit-quiz' slug=quiz.slug %}"
                           class="underline underline-offset-2 text-sm text-sky-500 font-semibold">
                            <i class="bi bi-pen"></i>
                        Edit Quiz</a>
                        <button onclick="openModal('delete_quiz_modal')"
                                class="underline underline-offset-2 text-sm text-red-500 font-semibold">
                            <i class="bi bi-trash3"></i>
                            Delete Quiz
                        </button>
                    </div>
                    {% include "quiz/delete_quiz_modal.html" with quiz_title=quiz.title modal_id="delete_quiz_modal" %}
                {% endif %}
            </div>
            <hr class="my-2">
            <div class="flex gap-2 items-center">
                <p class="font-semibold">
                    By
                    <i class="bi bi-person"></i>
                    <a href="#"
                       class="text-sky-600 underline underline-offset-2 cursor-pointer font-semibold">{{ quiz.created_by.username }}</a>
                </p>
                <p class="text-sm text-gray-300">|</p>
                <p class="font-semibold">
                    <i class="bi bi-question-circle"></i>
                    {{ quiz.questions.count }}
                    Questions
                </p>
                <p class="text-sm text-gray-300">|</p>
                <p class="font-semibold">
                    <i class="bi bi-stopwatch"></i>
                    3m24s
                    {% comment %} {{ quiz.total_duration|format_duration }} {% endcomment %}
                </p>
                <p class="text-sm text-gray-300">|</p>
                <p class="font-semibold">
                    <i class="bi bi-people"></i>
                    {{ quiz.participants.count }} Participants
                </p>
            </div>
        </div>
        <br class="my-8">
        <div class="flex gap-2">
            {% if quiz.created_by == request.user %}
                <a type="button"
                   class="my-2 rounded-full bg-sky-600 py-2 px-4 text-lg text-sky-200 hover:bg-sky-700 transition-colors focus:outline-double focus:ring focus:ring-3 font-semibold"
                   id="add-question-btn"
                   href="{% url 'quiz:add-question' slug=quiz.slug %}">
                    <i class="bi bi-plus-circle"></i>
                    Add Question
                </a>
                <button onclick="openModal('take_quiz_modal')"
                        hx-trigger="click"
                        hx-get="{% url 'quiz:take-quiz' slug=quiz.slug %}"
                        hx-target='#quiz-content'
                        hx-swap="outerHTML"
                        class="my-2 rounded-full bg-sky-300 py-2 px-4 text-lg text-sky-800 hover:bg-sky-500 transition-colors focus:outline-double focus:ring focus:ring-3 font-semibold">
                    <i class="bi bi-play-circle"></i>
                    Take Quiz
                </button>
            {% else %}
                <button onclick="openModal('take_quiz_modal')"
                        hx-trigger="click"
                        hx-get="{% url 'quiz:take-quiz' slug=quiz.slug %}"
                        hx-target='#quiz-content'
                        hx-swap="outerHTML"
                        class="my-2 rounded-full bg-sky-600 py-2 px-4 text-lg text-sky-200 hover:bg-sky-700 transition-colors focus:outline-double focus:ring focus:ring-3 font-semibold">
                    <i class="bi bi-play-circle"></i>
                    Take Quiz
                </button>
            {% endif %}
            {% include "quiz/take_quiz_modal.html" with question=quiz.questions.first %}
        </div>
    </div>
{% endblock content %}

templates/quiz/quiz_results.html
quiz completed

templates/quiz/take_quiz_modal.html
{% load quiz_tags %}
<div id="modal-backdrop"
     class="fixed left-0 top-0 w-screen h-screen hidden bg-black/50"></div>
<div id="take_quiz_modal"
     class="fixed top-0 left-0 w-full h-full flex items-center justify-center hidden">
     <div class="modal-dialog bg-white rounded shadow-lg w-full h-full">
          <div id="quiz-content" class="modal-content p-4 w-full">{% comment %}  {% endcomment %}</div>
          <button onclick="closeModal('take_quiz_modal')">close</button>
     </div>
</div>