core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quiz.urls")),
]

quiz/urls.py
from django.urls import path
from .views import (
    HomeView,
    CreateQuizView,
    QuizDetailView,
    QuizDeleteView,
    AddQuestionView,
    EditQuizView,
    QuizResultsView,
    take_quiz,
    get_question,
    submit_answer,
)


app_name = "quiz"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("create-quiz/", CreateQuizView.as_view(), name="create-quiz"),
    path("quiz/<str:slug>/", QuizDetailView.as_view(), name="quiz-detail"),
    path("quiz/<str:slug>/delete/", QuizDeleteView.as_view(), name="quiz-delete"),
    path("quiz/<str:slug>/edit/", EditQuizView.as_view(), name="edit-quiz"),
    path(
        "quiz/<str:slug>/add-question/", AddQuestionView.as_view(), name="add-question"
    ),
    path("quiz/<str:slug>/take-quiz/", take_quiz, name="take-quiz"),
    path("quiz/<str:slug>/question/", get_question, name="get-question"),
    path(
        "quiz/<str:slug>/submit-answer/<int:question_id>/",
        submit_answer,
        name="submit-answer",
    ),
    path("quiz/<str:slug>/results/", QuizResultsView.as_view(), name="quiz-results"),
]

templates/base.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="dark">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock title %}
        - DjQuiz</title>
        {% compress css %}
            <link rel="stylesheet" href="{% static 'style/output.css' %}">
            <link rel="stylesheet" href="{% static 'style/main.css' %}">
        {% endcompress %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;900&display=swap"
              rel="stylesheet">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="font-inter">
        {% include "navbar.html" %}
        {% block content %}
        {% endblock content %}
        <script src="//unpkg.com/htmx.org@1.9.10"></script>
        <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
        {% block js %}
        {% endblock js %}
        {% compress js %}
            <script src="{% static 'js/main.js' %}"></script>
        {% endcompress %}
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}
    Home
{% endblock title %}
{% block content %}
    <div class="p-12 flex flex-col">
        <div class="quizzes">
            {% for quiz in quizzes %}
                <div class="border p-3 shadow flex flex-col w-3/4 rounded-lg mb-3">
                    <a class="text-xl font-semibold text-sky-700"
                       href="{% url 'quiz:quiz-detail' slug=quiz.slug %}">{{ quiz.title }}</a>
                    <p class="text-sm">{{ quiz.description }}</p>
                    <hr class="my-2">
                    <p>{% lorem 1 b random %}</p>
                </div>
            {% endfor %}
        </div>
        {% comment %} <a class="bg-sky-700 hover:bg-sky-600 transition-colors duration-800 text-white font-bold py-2 px-4 rounded shadow" href="{% url 'quiz:create-quiz' %}">Create new Quiz</a> {% endcomment %}
    </div>
{% endblock content %}

templates/modal_base.html
<div id="modal-backdrop"
     class="fixed left-0 top-0 w-screen h-screen hidden bg-black/50"></div>
<div id="{{ modal_id }}"
     class="fixed top-0 left-0 w-full h-full flex items-center justify-center hidden">
    <div class="modal-dialog bg-white rounded shadow-lg sm:w-2/3 md:w-1/2 lg:w-1/3 xl:w-1/3">
        <div class="modal-content p-4 w-full">
            <h2 class="text-xl font-bold">
                {% block modal_title %}
                {% endblock modal_title %}
            </h2>
            <hr class="my-2">
            {% block modal_content %}
            {% endblock modal_content %}
            <hr class="my-2">
            {% block modal_footer %}
            {% endblock modal_footer %}
        </div>
    </div>
</div>

templates/navbar.html
<nav class="bg-gray-200 text-gray-800 py-2">
    <div class="container mx-auto px-4 py-2">
        <div class="flex items-center justify-between">
            <a class=" font-bold text-xl font-serif" href="{% url 'quiz:home' %}">DjQuiz</a>
            <div class="flex items-center font-semibold">
                <a class="mr-4 hover:text-gray-900 hover:underline hover:underline-offset-4"
                   href="#">Home</a>
                <a class="mr-4 hover:text-gray-900 hover:underline hover:underline-offset-4"
                   href="#">My Quizzes</a>
            </div>
        </div>
    </div>
</nav>